package com.travelogue.entities;

import lombok.Getter;
import lombok.Setter;

import com.googlecode.objectify.annotation.Entity;
import com.googlecode.objectify.annotation.Id;

/**
 * An entity for messsages sent from the web console to the registered devices
 * 
 * Its associated endpoint, MessageEndpoint.java, was NOT automatically generated 
 * from this class. While it is easy to generate endpoints automatically, you can
 * write an endpoint manually without generating it. You still need to generate
 * the associated client library from the endpoint when changes are made.
 * 
 * For more information on endpoints, see
 * http://developers.google.com/eclipse/docs/cloud_endpoints.
 */

@Entity
public class MessageData {

  /*
   * Autogenerated primary key
   */
  @Id
  @Getter
  private Long id;
  
  /*
   * The text of the message sent
   */
  @Getter
  @Setter
  private String message;

  /*
   * Timestamp indicating when this device registered with the application.
   */
  @Getter
  @Setter
  private long timestamp;
  
}
